name: CI/CD Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      DOCKER_IMAGE_NAME: ${{ steps.set_image_name.outputs.DOCKER_IMAGE_NAME }}
      DOCKER_IMAGE_TAG: ${{ steps.set_image_name.outputs.DOCKER_IMAGE_TAG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set image name and tag
        id: set_image_name
        run: |
          # Use Docker Hub username and repository name for the image
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}"
          echo "DOCKER_IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "DOCKER_IMAGE_TAG=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.set_image_name.outputs.DOCKER_IMAGE_NAME }}:${{ steps.set_image_name.outputs.DOCKER_IMAGE_TAG }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # This script will install Docker and Docker Compose if they are not found.
            # IMPORTANT: The SSH user ('${{ secrets.SSH_USERNAME }}') must have passwordless sudo configured on the server.

            # Install Docker if not present
            if ! command -v docker &> /dev/null; then
                echo "Docker not found. Installing..."
                sudo apt-get update
                sudo apt-get install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
            fi

            # Install Docker Compose if not present
            if ! command -v docker-compose &> /dev/null; then
                echo "Docker Compose not found. Installing..."
                sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
            fi

            # --- Application Deployment ---
            APP_DIR=~/app
            REPO_URL=${{ github.event.repository.html_url }}

            mkdir -p $APP_DIR
            cd $APP_DIR

            # Always download the latest docker-compose.yml to avoid mismatches
            echo "Downloading latest docker-compose.yml..."
            curl -f -L -o docker-compose.yml $REPO_URL/raw/main/docker-compose.yml

            # Simplify docker-compose.yml interpolation to prevent parsing errors
            echo "Simplifying docker-compose.yml interpolation..."
            sed -i 's/${DOCKER_IMAGE_TAG:-latest}/${DOCKER_IMAGE_TAG}/g' docker-compose.yml

            # Log in to Docker Hub
            echo "Logging in to Docker Hub..."
            echo ${{ secrets.DOCKERHUB_TOKEN }} | sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            if [ $? -ne 0 ]; then
              echo "Error: Docker login failed. Check DOCKERHUB_USERNAME and DOCKERHUB_TOKEN secrets."
              exit 1
            fi
            echo "Login successful."

            # Create .env file for docker-compose to use
            echo "Creating .env file for docker-compose..."
            echo "DOCKER_IMAGE_NAME=${{ needs.build-and-push.outputs.DOCKER_IMAGE_NAME }}" > .env
            echo "DOCKER_IMAGE_TAG=${{ needs.build-and-push.outputs.DOCKER_IMAGE_TAG }}" >> .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
            echo "STORAGE_TYPE=${{ secrets.STORAGE_TYPE }}" >> .env
            echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> .env
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
            echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
            echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
            echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
            echo "GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> .env
            echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}" >> .env
            echo "NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}" >> .env
            echo "NAVER_REDIRECT_URI=${{ secrets.NAVER_REDIRECT_URI }}" >> .env
            echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
            echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> .env
            echo "KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> .env

            echo "Pulling Docker images..."
            sudo docker-compose pull
            if [ $? -ne 0 ]; then
              echo "Error: docker-compose pull failed. Check image name and permissions."
              exit 1
            fi

            # Start the services
            echo "Starting services with docker-compose..."
            sudo docker-compose up -d
